### PR TITLE
Added two Apple tv icons

### PR DESCRIPTION
**Pull request by LRvdLinden**
appletv

and dark version

### CODE REVIEW

**Comment by hulkhaugen** [comment]
I suggest simplifying it, as it normally is displayed very small.
- The svg file you provided is a bit of a mess, and has the wrong sizes.
- The actual svg content goes in the `/dist/hass-bha-icons.js` file, the additional svg file is just for preview here on GitHub.
- The name in the `README.md` should be the same as the `key` in the js-file above. That would be the name that you use in HA, and it should be lowercase and no spaces, like `apple-tv` for instance.

This is an ok example:

image

**Comment by LRvdLinden** [comment]
Okay. Can you add this one?

**Comment by LRvdLinden** [comment]
I will close my PR

**Comment by hulkhaugen** [comment]
Yes, I will add it

**Comment by LRvdLinden** [comment]
Thanks a lot!!

**Pull request closed without merging**
