### PR TITLE
Adding new icons

### PR DESCRIPTION
**Pull request by clemalex824**
- DSM
- NAS
- Nginx Proxy Manager
- Node-RED
- OpenWRT
- Phoscom

### CODE REVIEW

**Comment by clemalex824** [comment]
As agreed : https://github.com/hulkhaugen/hass-bha-icons/issues/17#issuecomment-817261391

**Comment by m1ke-hub** [comment]
Hey @clemalex824 I just wanted to note that it is called Phoscon and not Phoscom. [Link to Homepage](https://www.phoscon.de/en/app/doc)

**Comment by clemalex824** [comment]
> I just wanted to note that it is called Phoscon and not Phoscom.


well seen ! it's correct now (I think 😶)

**Comment by m1ke-hub** [comment]
> well seen ! it's correct now (I think 😶)

@clemalex824 Seems good yeah - except in the readme (preview is referring to the correct name, but the icon description is still phoscom) 😊

Edit: now it's good! Good work 👍

**Comment by clemalex824** [comment]
I added the icon for the coil (filament).

I don't touch anymore because I only do stupid things  😅

**Review by hulkhaugen — APPROVED** [review]
Updated and added new icons

**Pull request merged**
